image: amazoncorretto:17.0.2-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew build -x test --stacktrace
  artifacts:
    paths:
      - 'build/libs/'

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport --stacktrace
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' build/reports/jacoco/test/jacocoTestReport.csv
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit: 'build/test-results/test/**/TEST-*.xml'

javadoc:
  stage: deploy
  script:
    - ./gradlew javadoc
    - cp -r build/docs/javadoc .
    - mv javadoc public
  artifacts:
    paths:
      - 'public'