image: amazoncorretto:17.0.2-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test --stacktrace
  artifacts:
    paths:
      - 'build/libs/'

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport --stacktrace
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - 'build/reports/jacoco/test/html/index.html'
    reports:
      junit: 'build/test-results/test/**/TEST-*.xml'
