stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test --stacktrace
  artifacts:
    paths:
      - 'build/libs/'

test:
  stage: test
  script:
    - ./gradlew test --stacktrace
  artifacts:
    reports:
      junit: 'build/test-results/test/**/TEST-*.xml'